export enum ActionType {
  // Repositories page
  SEARCH_REPOSITORIES_START = "SEARCH_REPOSITORIES_START",
  SEARCH_REPOSITORIES_SUCCESS = "SEARCH_REPOSITORIES_SUCCESS",
  SEARCH_REPOSITORIES_FAILURE = "SEARCH_REPOSITORIES_FAILURE",
}
